config/routes.rb
Rails.application.routes.draw do
  root 'search#find_comments'
  get 'search/find_reply'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def find_comments
    @url =  ""
    @sort = "relevance"

    if params[:url].present?

      @url = params[:url]
      @sort = params[:sort]

      if params[:num].nil?
        @num = 0
        @video_id = YoutubeApi.format_url(@url)
        if @video_id.nil?
          @comments = "このURLの動画は存在しません"
          return
        end
      else
        @num = params[:num].to_i + 1
        @video_id = params[:video_id]
      end

      begin
        @comments = []
        @page_token = params[:page_token]
        20.times do
          res_body = YoutubeApi.comments(@video_id, 100, @sort, @page_token)
          res_body["items"].each do |item|
            text_display = item["snippet"]["topLevelComment"]["snippet"]["textDisplay"]
            # if Translation.detect(text_display) == "ja"
            if text_display =~ /(?:\p{Hiragana})/
              hash = {}
              hash[:id] = item["id"]
              hash[:author_display_name] = item["snippet"]["topLevelComment"]["snippet"]["authorDisplayName"]
              hash[:author_profile_image_url] = item["snippet"]["topLevelComment"]["snippet"]["authorProfileImageUrl"]
              hash[:like_count] = item["snippet"]["topLevelComment"]["snippet"]["likeCount"]
              hash[:published_at] = item["snippet"]["topLevelComment"]["snippet"]["publishedAt"]
              hash[:text_display] = text_display
              hash[:total_reply_count] = item["snippet"]["totalReplyCount"]
              @comments << hash
            end
          end
          @page_token = res_body["nextPageToken"]
          break if @comments.size >= 50 || @page_token.nil?
        end
      rescue
        @comments = "このIDの動画は存在しません。"
        return
      end
    else
      @comments = "URLを入力してください。"
      @num = 0
      return
    end
  end
  
  def find_reply
    @comment_id = params[:comment_id]
    @replies = YoutubeApi.all_replies(@comment_id, 100, 500)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/test_view_helper.rb
module TestViewHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>comment_filter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/search/_comment_list.html.erb
<% if @comments.empty? %>

	<div style="margin-top: 200px; text-align: center;">
		<span>1000件以内に日本語のコメントはありませんでした。</span>
	</div>

<% elsif @comments.is_a?(String) %>
	<div style="margin-top: 200px; text-align: center;">
		<span><%= @comments %></span>
	</p>

<% else %>
	<% if @num == 0 %>
		<div class="headspace"></div>
	<% end %>
	<% @comments.each do |comment| %>
		<section class="comment">
			<div class="comment_author_profile_image">
				<img src="<%= comment[:author_profile_image_url] %>" alt="プロフィール画像お">
			</div>
			<div class="comment_main">
				<div class="comment_header">
					<span><%= comment[:author_display_name] %></span>
					<span>　<%= time_ago_in_words(comment[:published_at]) %>前</span>
				</div>
				<div class="comment_body">
					<span><%= simple_format(comment[:text_display]) %></span>
				</div>
				<div class="comment_body_renderer">
					<span>続きを読む</span>
				</div>
				<div class="comment_like_count">
					<span><i class="fas fa-thumbs-up"></i> <%= comment[:like_count] %></span>
				</div>
				<div class="comment_replies" id="comment_replies_<%= comment[:id] %>">
					<% if comment[:total_reply_count] > 0 %>
						<div class="replies_renderer">
							<span>
								<%= link_to search_find_reply_path(comment_id: comment[:id]), remote: :true do %>
									<i class="fas fa-chevron-down"></i> <%= comment[:total_reply_count] %>件の返信を表示
								<% end %>
							</span>
						</div>
						<div class="cv-spinner">
							<span class="spinner"></span>
						</div>
					<% end %>
				</div>
			</div>
		</section>
	<% end %>
	<% if @page_token %>
		<div id="comment_list_<%= @num + 1 %>" class="comment_list">
			<div class="next_page">
				<span><%= link_to "他のコメントを表示", root_path(url: @url, video_id: @video_id, sort: @sort, page_token: @page_token, num: @num), remote: :true %></span>
				<div class="cv-spinner">
					<span class="spinner"></span>
				</div>
			</div>
		</div>
	<% end %>

	<script>
		$(function() {
			$('.replies_renderer span').on('click', function() {
				$(this).parent().next().css('display', 'flex');
			});
			$('.next_page span').on('click', function() {
				$('.next_page .cv-spinner').css('display', 'flex');
			});
		});
	</script>

<% end %>

<div class="filter"></div>

<div class="cv-spinner-large">
	<span class="spinner-large"></span>
</div>	

app/views/search/_replies.html.erb
<div class="replies_renderer">
	<div class="replies_renderer_active">
		<span><i class="fas fa-chevron-up"></i> 返信を非表示</span>
	</div>
</div>
<% @replies.reverse_each do |reply| %>
	<section class="reply">
		<div class="reply_author_profile_image">
			<img src='<%= reply["snippet"]["authorProfileImageUrl"] %>' alt="">
		</div>
		<div class="comment_main">
			<div class="comment_header">
				<span><%= reply["snippet"]["authorDisplayName"] %></span>
				<span><%= time_ago_in_words(reply["snippet"]["publishedAt"]) %>前</span>
			</div>
			<div class="comment_body">
				<span><%= simple_format(reply["snippet"]["textDisplay"]) %></span>
			</div>
			<div class="comment_like_count">
				<span><i class="fas fa-thumbs-up"></i> <%= reply["snippet"]["likeCount"] %></span>
			</div>
		</div>
	</section>
<% end %>

app/views/search/find_comments.html.erb
<%= form_with url: root_path, method: :get do |f| %>

<div class="form_container">
    <div class="input-wrapper">
			<%= f.text_field :url, placeholder: "Enter the URL", value: @url, class: "search" %>
      <div id="magnify" v-on:click="search"><svg class="icon icon--search  type_1"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-search"></use></svg></div>
		</div>
</div>

<svg class="hidden">
	<defs>
		<symbol id="icon-search" viewBox="0 0 24 24">
			<title>search</title>
			<path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
		</symbol>
	</defs>
</svg>

<div class="radio-container">
	<ul>
		<li>
			<% if @sort == "relevance" %>
				<%= f.radio_button :sort, :relevance, checked: true %>
			<% else %>
				<%= f.radio_button :sort, :relevance %>
			<% end %>
			<%= f.label :sort_relevance, "評価順" %>
			
			<div class="check"></div>
		</li>
		
		<li>
			<% if @sort == "time" %>
				<%= f.radio_button :sort, :time, checked: true %>
			<% else %>
				<%= f.radio_button :sort, :time %>
			<% end %>
			<%= f.label :sort_time, "新着順" %>
			
			<div class="check"></div>
		</li>
	</ul>
</div>

<%= f.submit "submit", class: "submit type_1" %>

<% end %>

<div id="comment_list_0">
	<div class="cv-spinner-large">
		<span class="spinner-large"></span>
	</div>
</div>

app/views/search/find_comments.js.erb
$("#comment_list_<%= @num %>").html("<%= j(render 'comment_list') %>");

app/views/search/find_reply.js.erb
$("#comment_replies_<%= @comment_id %>").html("<%= j(render 'replies') %>");

app/views/search/find_videos.html.erb
<%= form_with url: root_path, method: :get, local: true do |f| %>
	<%= f.text_field :video_id, placeholder: "VIDEO ID", value: @video_id %>
	<% if @sort == "評価順" %>
		<%= f.radio_button :sort, :評価順, checked: true %>
	<% else %>
		<%= f.radio_button :sort, :評価順 %>
	<% end %>
	<%= f.label :sort_評価順, "評価順" %>
	<% if @sort == "新着順" %>
		<%= f.radio_button :sort, :新着順, checked: true %>
	<% else %>
		<%= f.radio_button :sort, :新着順 %>
	<% end %>
	<%= f.label :sort_新着順, "新着順" %>
	<%= f.submit "検索" %>
<% end %>
<% if @comments %>
	<table border="1">
		<thead>
			<tr>
				<th>名前</th>
				<th>コメント</th>
			</tr>
		</thead>
		<tbody>
		<% @comments.each do |comment| %>
			<% if comment.snippet.top_level_comment.snippet.text_display =~ /(?:\p{Hiragana}|\p{Katakana}|[一-龠々])/ %>
			<tr>
				<td width="100px"><%= comment.snippet.top_level_comment.snippet.author_display_name %></td>
				<td><%= comment.snippet.top_level_comment.snippet.text_display %></td>
			</tr>
			<% end %>
		<% end %>
		</tbody>
	</table>
<% end %>